[package]
name = "syml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[test]]
name = "parse_test"
path = "tests/parse_test.rs"
harness = false

[features]
default = []
serde_impl = ["serde", "serde/derive", "linked-hash-map/serde_impl"]

[dependencies]
linked-hash-map = "0.5.6"
peg = "0.8.2"
serde = { version = "1.0.197", optional = true }
unicode-ident = "1.0.12"

[dev-dependencies]
serde_json = "1.0.115"
